datacenters:
- id: 0
  name: null
  amount: 1
  architecture: "x86"
  os: "Linux"
  vmm: "Xen"
  timeZone: 0.0
  vmAllocationPolicy: null
  vmMigration: false
  hosts: []
  costPerSec: 0.0
  costPerMem: 0.0
  costPerStorage: 0.0
  costPerBw: 0.0
  sans: []
  upperUtilizationThreshold: 0.0
  lowerUtilizationThreshold: 0.0
  schedulingInterval: 0.0

customers:
- id: 0
  name: null
  amount: 1
  vms: []
  cloudlets: []
